coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: exclude
    project:
      default:
        target: auto
      demo:
        target: auto
        flags:
          - demo
      index:
        target: auto
        flag_coverage_not_uploaded_behavior: pass
        flags:
          - index
      missing:
        flags:
          - missing
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
  show_carryforward_flags: false

flags:
  demo:
    paths:
      - src/demo/demo.py
    carryforward: false
  index:
    paths:
      - src/index/index.py
    carryforward: true
  missing:
    carryforward: false